spring.datasource.url=${NEON_DB_URL}
spring.datasource.username=${NEON_DB_USER}
spring.datasource.password=${NEON_DB_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

loggin.level.root=INFO
loggin.level.com.gestion.eventos=INFO
loggin.level.org.springframework=INFO
tern.console=%d{yyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) %cyan(%logger{36}) - %msg%n